#!/usr/bin/env bash
# Script pour visualiser la structure du projet Immo2000 avec authentification

echo "🏗️  Structure du projet Immo2000 (avec authentification JWT)"
echo
echo "immo2000/"
echo "├── 📄 README.md                          (👈 Commencez ici!)"
echo "├── 📄 QUICKSTART_AUTH.md                (🔐 Authentification: 5 min)"
echo "├── 📄 AUTHENTICATION.md                 (🔐 Authentification: Documentation)"
echo "├── 📄 AUTHENTICATION_DIAGRAMS.md        (🔐 Authentification: Diagrammes)"
echo "├── 📄 AUTH_SUMMARY.md                  (🔐 Authentification: Résumé)"
echo "├── 📄 INTEGRATION_CHECKLIST.md          (✅ Checklist d'intégration)"
echo "├── 📄 PROJECT_STATUS.md                 (📊 État du projet)"
echo "├── 📄 INTEGRATION_GUIDE.md              (🔗 Guide d'intégration)"
echo "├── 📄 STRUCTURE.md                      (📁 Structure des fichiers)"
echo "├── 📄 .gitignore"
echo "│"
echo "├── 📁 backend/                          (🔧 Backend Python Flask)"
echo "│   ├── 📄 requirements.txt              (+ bcrypt)"
echo "│   ├── 📄 pytest.ini"
echo "│   ├── 📄 .flake8"
echo "│   ├── 📄 .env.example                  (+ JWT_SECRET_KEY)"
echo "│   │"
echo "│   ├── 📁 src/"
echo "│   │   ├── 📄 __init__.py"
echo "│   │   ├── 📄 app.py                    (✏️ Intégré SQLAlchemy + auth)"
echo "│   │   ├── 📄 config.py                 (✏️ + JWT config)"
echo "│   │   ├── 📄 melo_api.py"
echo "│   │   │"
echo "│   │   ├── 📁 auth/                     (🔐 NOUVEAU - Authentification)"
echo "│   │   │   ├── 📄 __init__.py"
echo "│   │   │   ├── 📄 models.py            (User SQLAlchemy)"
echo "│   │   │   ├── 📄 utils.py             (JWT + bcrypt)"
echo "│   │   │   ├── 📄 decorators.py        (@token_required, @role_required)"
echo "│   │   │   └── 📄 routes.py            (/auth/* endpoints)"
echo "│   │   │"
echo "│   │   ├── 📁 routes/                   (À implémenter)"
echo "│   │   │   ├── biens.py"
echo "│   │   │   ├── estimations.py"
echo "│   │   │   └── utilisateurs.py"
echo "│   │   │"
echo "│   │   ├── 📁 services/"
echo "│   │   │   └── melo_service.py"
echo "│   │   │"
echo "│   │   ├── 📁 models/"
echo "│   │   │   ├── bien.py"
echo "│   │   │   ├── estimation.py"
echo "│   │   │   └── etc."
echo "│   │   │"
echo "│   │   ├── 📁 utils/"
echo "│   │   │   ├── validators.py"
echo "│   │   │   └── helpers.py"
echo "│   │   │"
echo "│   │   └── 📁 database.py              (À implémenter)"
echo "│   │"
echo "│   ├── 📁 tests/"
echo "│   │   ├── 📄 __init__.py"
echo "│   │   ├── 📄 conftest.py"
echo "│   │   ├── 📄 test_melo_api.py"
echo "│   │   └── 📄 test_auth.py             (🧪 NOUVEAU - 20+ tests)"
echo "│   │"
echo "│   └── 📁 scripts/                      (🚀 Scripts d'aide)"
echo "│       ├── 📄 test_auth_quick.py       (⚡ Test rapide)"
echo "│       └── 📄 setup.sh                 (🔧 Setup complet)"
echo "│"
echo "├── 📁 database/"
echo "│   ├── 📄 immo2000_schema.sql          (PostgreSQL: 8 tables)"
echo "│   ├── 📄 README.md"
echo "│   ├── 📄 SCHEMA_DIAGRAM.md"
echo "│   ├── 📄 GUIDE_ARCHITECTURE_DB.md"
echo "│   ├── 📄 INTEGRATION_MELO.md          (Intégration API)"
echo "│   └── 📄 test_integration.py"
echo "│"
echo "├── 📁 devops/"
echo "│   ├── 📄 docker-compose.yml"
echo "│   ├── 📄 Dockerfile.backend"
echo "│   ├── 📄 nginx.conf"
echo "│   └── 📄 README.md"
echo "│"
echo "├── 📁 frontend/"
echo "│   └── 📄 README.md                    (À implémenter)"
echo "│"
echo "├── 📁 docs/"
echo "│   ├── 📄 ARCHITECTURE.md"
echo "│   └── 📄 API.md"
echo "│"
echo "└── 📁 scripts/"
echo "    ├── 📄 setup.sh                     (🔧 Setup complet)"
echo "    └── 📄 deploy.sh                    (🚀 Déploiement)"
echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 AUTHENTIFICATION JWT - NOUVEAU!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
echo "✅ Module complet créé :"
echo "   • backend/src/auth/         (4 fichiers)"
echo "   • backend/tests/test_auth.py (20+ tests)"
echo "   • Documentation (3 fichiers) + diagrammes (8)"
echo
echo "🚀 Pour démarrer :"
echo "   1. cd backend"
echo "   2. pip install -r requirements.txt"
echo "   3. python scripts/test_auth_quick.py"
echo "   4. python -m flask run"
echo
echo "📚 Documentation :"
echo "   • QUICKSTART_AUTH.md (5 min)"
echo "   • AUTHENTICATION.md (complète)"
echo "   • AUTHENTICATION_DIAGRAMS.md (visuels)"
echo
echo "🔒 Endpoints :"
echo "   • POST /auth/register    - S'inscrire"
echo "   • POST /auth/login       - Se connecter"
echo "   • POST /auth/refresh     - Rafraîchir le token"
echo "   • GET /auth/me           - Infos utilisateur"
echo
echo "🛡️  Sécurité :"
echo "   ✓ bcrypt 12 rounds"
echo "   ✓ JWT HS256"
echo "   ✓ Tokens court-lived (24h + 7j)"
echo "   ✓ Validation stricte"
echo "   ✓ @token_required, @role_required"
echo
